import "server-only";

import { dayRange } from "@/lib/tasks/due";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import type { TaskPriority, TaskRow, TaskView } from "./types";

const SELECT = `
  id, title, description, due_at, status, priority, is_auto_generated, completed_at,
  assignee:profiles!tasks_assignee_id_fkey(id, full_name),
  contact:contacts(id, first_name, last_name),
  company:companies(id, name),
  deal:deals(id, title)
`;

type RawTask = {
  id: string;
  title: string;
  description: string | null;
  due_at: string | null;
  status: TaskRow["status"];
  priority: TaskPriority;
  is_auto_generated: boolean;
  completed_at: string | null;
  assignee: { id: string; full_name: string | null } | null;
  contact: { id: string; first_name: string | null; last_name: string | null } | null;
  company: { id: string; name: string } | null;
  deal: { id: string; title: string } | null;
};

function toTask(row: RawTask): TaskRow {
  const contactName = row.contact
    ? [row.contact.first_name, row.contact.last_name].filter(Boolean).join(" ").trim()
    : "";

  return {
    id: row.id,
    title: row.title,
    description: row.description,
    dueAt: row.due_at,
    status: row.status,
    priority: row.priority,
    isAutoGenerated: row.is_auto_generated,
    completedAt: row.completed_at,
    assignee: row.assignee ? { id: row.assignee.id, name: row.assignee.full_name } : null,
    link: row.deal
      ? { kind: "deal", id: row.deal.id, label: row.deal.title }
      : row.contact
        ? { kind: "contact", id: row.contact.id, label: contactName }
        : row.company
          ? { kind: "company", id: row.company.id, label: row.company.name }
          : null,
  };
}

export type TaskFilters = {
  view: TaskView;
  assigneeId: string | null;
  priority: TaskPriority | null;
};

/**
 * One tab's worth of tasks.
 *
 * The date boundaries are computed in the organization's timezone and sent as
 * instants, so "today" means the team's today rather than the server's. The
 * overdue test is `due_at < now`, evaluated here on every request — nothing is
 * ever stored, so nothing can go stale.
 */
export async function listTasks(
  organizationId: string,
  timeZone: string,
  now: Date,
  filters: TaskFilters,
  limit = 100,
): Promise<TaskRow[]> {
  const supabase = await createSupabaseServerClient();
  const today = dayRange(now, timeZone);

  let request = supabase.from("tasks").select(SELECT).eq("organization_id", organizationId);

  switch (filters.view) {
    case "overdue":
      request = request
        .eq("status", "open")
        .lt("due_at", now.toISOString())
        .order("due_at", { ascending: true });
      break;
    case "today":
      request = request
        .eq("status", "open")
        .gte("due_at", now.toISOString())
        .lt("due_at", today.to.toISOString())
        .order("due_at", { ascending: true });
      break;
    case "upcoming":
      // Undated tasks live here rather than nowhere. `nullsFirst: false` is
      // what puts them at the bottom, which is the rule from the plan.
      request = request
        .eq("status", "open")
        .or(`due_at.gte.${today.to.toISOString()},due_at.is.null`)
        .order("due_at", { ascending: true, nullsFirst: false });
      break;
    case "completed":
      request = request
        .eq("status", "completed")
        .gte("completed_at", new Date(now.getTime() - 30 * 86_400_000).toISOString())
        .order("completed_at", { ascending: false });
      break;
  }

  if (filters.assigneeId) request = request.eq("assignee_id", filters.assigneeId);
  if (filters.priority) request = request.eq("priority", filters.priority);

  // Every sort above ends in id, so rows never swap places between requests.
  const { data, error } = await request.order("id", { ascending: true }).limit(limit);
  if (error || !data) return [];

  return (data as unknown as RawTask[]).map(toTask);
}

/** Tasks attached to one record, for the widget on its detail page. */
export async function listTasksFor(
  organizationId: string,
  link: { contactId?: string; companyId?: string; dealId?: string },
): Promise<TaskRow[]> {
  const supabase = await createSupabaseServerClient();

  let request = supabase
    .from("tasks")
    .select(SELECT)
    .eq("organization_id", organizationId)
    .eq("status", "open");

  if (link.contactId) request = request.eq("contact_id", link.contactId);
  if (link.companyId) request = request.eq("company_id", link.companyId);
  if (link.dealId) request = request.eq("deal_id", link.dealId);

  const { data, error } = await request
    .order("due_at", { ascending: true, nullsFirst: false })
    .order("id", { ascending: true })
    .limit(10);

  if (error || !data) return [];
  return (data as unknown as RawTask[]).map(toTask);
}

/**
 * Counts for the tab labels and the sidebar badge.
 *
 * Deliberately NOT cached. The number is per-user and per-tenant, and a shared
 * cache keyed on neither is how one org ends up seeing another's count. It is
 * a single count over a partial index — cheaper than the cache lookup would be.
 */
export async function getTaskCounts(
  organizationId: string,
  timeZone: string,
  now: Date,
  assigneeId: string | null,
): Promise<{ overdue: number; today: number }> {
  const supabase = await createSupabaseServerClient();
  const today = dayRange(now, timeZone);

  const base = () => {
    const request = supabase
      .from("tasks")
      .select("id", { count: "exact", head: true })
      .eq("organization_id", organizationId)
      .eq("status", "open");
    return assigneeId ? request.eq("assignee_id", assigneeId) : request;
  };

  const [overdue, dueToday] = await Promise.all([
    base().lt("due_at", now.toISOString()),
    base().gte("due_at", now.toISOString()).lt("due_at", today.to.toISOString()),
  ]);

  return { overdue: overdue.count ?? 0, today: dueToday.count ?? 0 };
}

export type AutomationSettings = {
  leadTaskEnabled: boolean;
  leadTaskTitle: string;
  leadTaskOffsetDays: number;
};

export async function getAutomationSettings(
  organizationId: string,
): Promise<AutomationSettings | null> {
  const supabase = await createSupabaseServerClient();
  const { data, error } = await supabase
    .from("automation_settings")
    .select("lead_task_enabled, lead_task_title, lead_task_offset_days")
    .eq("organization_id", organizationId)
    .maybeSingle();

  if (error || !data) return null;
  return {
    leadTaskEnabled: data.lead_task_enabled,
    leadTaskTitle: data.lead_task_title,
    leadTaskOffsetDays: data.lead_task_offset_days,
  };
}
