import type { Database } from "@/types/database";

export type TaskStatus = Database["public"]["Enums"]["task_status"];
export type TaskPriority = Database["public"]["Enums"]["task_priority"];

export const TASK_PRIORITIES = ["low", "normal", "high"] as const satisfies readonly TaskPriority[];

/** The tabs on /tasks. `overdue` is the landing tab when it is not empty. */
export const TASK_VIEWS = ["overdue", "today", "upcoming", "completed"] as const;
export type TaskView = (typeof TASK_VIEWS)[number];

export type TaskLink =
  | { kind: "contact"; id: string; label: string }
  | { kind: "company"; id: string; label: string }
  | { kind: "deal"; id: string; label: string }
  | null;

export type TaskRow = {
  id: string;
  title: string;
  description: string | null;
  dueAt: string | null;
  status: TaskStatus;
  priority: TaskPriority;
  isAutoGenerated: boolean;
  completedAt: string | null;
  assignee: { id: string; name: string | null } | null;
  link: TaskLink;
};

export const LINK_PATH: Record<"contact" | "company" | "deal", string> = {
  contact: "/contacts",
  company: "/companies",
  deal: "/deals",
};
